modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility/issues"

[[mods]]
modId="allthecompatibility"
version="1.5.0"
displayName="All The Compatibility"
itemIcon="minecraft:crafting_table"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AllTheCompatibility.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds recipe compatibility between AllTheOres and other mods!
'''

[[dependencies.allthecompatibility]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="alltheores"
    mandatory=true
    versionRange="[1.7.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"




[[dependencies.allthecompatibility]]
    modId="voluminousenergy"
    mandatory=false
    versionRange="[1.18-0.2.3.1,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="indreb"
    mandatory=false
    versionRange="[1.18.1-0.11.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="assemblylinemachines"
    mandatory=false
    versionRange="[1.18-1.3.5,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="create"
    mandatory=false
    versionRange="[0.4,)"
    ordering="BEFORE"
    side="BOTH"
