modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility/issues"

[[mods]]
modId="allthecompatibility"
version="1.2.0"
displayName="All The Compatibility"
itemIcon="minecraft:redstone"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AllTheCompatibility.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds recipe compatibility between AllTheOres and other mods!
'''

[[dependencies.allthecompatibility]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="alltheores"
    mandatory=true
    versionRange="[1.7.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"
